spring:
  mail:
    host: smtp-mail.outlook.com
    username: alexandria-crescer@outlook.com
    password: tcc-crescer
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/alexandria
    username: alexandria
    password: alexandria
  jpa:
    hibernate:
      ddl-auto: validate

server:
  error:
    include-message: always
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.security: DEBUG
